<a href="https://colab.research.google.com/github/Joykareko/Deep-Learning-Projects/blob/main/00_Intro_to_Tensor_flow_with_Bourke_on_YT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Introduction to Tensors
2.Getting Info from tensors
3.Manipultaing tensors
4. Tensors and Numpy
5. Using tf.function( a way to speed up the python function)
6. Using GPUs with tensorflow
7. Exercises


**Introduction to Tensors**

In [1]:
#importing tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [3]:
#creating tensors/instance
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#checking the ndim of a tensor (number of dimensions)
scalar.ndim

0

In [5]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [10]:
#create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [15]:
matrix_2 = tf.constant([[10.,7.],
                        [10.,8.],
                        [9.,12.]] ,dtype = tf.float16)

matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [10.,  8.],
       [ 9., 12.]], dtype=float16)>

In [16]:
matrix_2.ndim

2

In [ ]:
#creating a tensor
